FROM node:22
RUN apt-get update \
  && apt-get install -y --no-install-recommends python3 python3-pip python3-venv python3-full curl \
  && rm -rf /var/lib/apt/lists/* \
  && npm install -g pnpm@latest
ENV CI=true
WORKDIR /workspace
